version: "3.9"

services:
  db:
    image: mysql:8.4.5
    container_name: fastapi_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskmanagerdatabase
      MYSQL_USER: taskmanager
      MYSQL_PASSWORD: taskmanagerpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: